#!/usr/bin/env node
"use strict";
/**
 * FDD Protect Hook - Auto-generated by fdd-cli
 * DO NOT EDIT MANUALLY - regenerated on each fdd add
 *
 * Intercepts Write/Edit tool calls and blocks/warns based on
 * protect rules defined in .fdd/pits/
 */

const { minimatch } = require("minimatch");
const fs = require("node:fs");
const path = require("node:path");

const PROTECT_RULES = [
	{
		pitfallId: "PIT-000",
		pitfallTitle: "[示例] 保护 templates 构建产物",
		triggerIndex: 0,
		paths: ["templates/**"],
		exclude: [],
		permissions: {
			create: "deny",
			update: "deny",
			delete: "deny",
		},
		message: "templates/ 是构建产物，请修改 src/templates/ 后运行 bun build",
	},
];

let inputData = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (chunk) => {
	inputData += chunk;
});
process.stdin.on("end", () => {
	try {
		processToolCall(JSON.parse(inputData));
	} catch (_error) {
		process.exit(0);
	}
});

function processToolCall(input) {
	const { tool_input } = input;
	const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();

	const filePath = tool_input?.file_path || tool_input?.path || "";
	if (!filePath) {
		outputAllow();
		return;
	}

	// Normalize to relative path
	let relativePath = filePath;
	if (path.isAbsolute(filePath)) {
		relativePath = path.relative(projectDir, filePath);
	}

	const isCreate = !fs.existsSync(path.resolve(projectDir, relativePath));
	const operation = isCreate ? "create" : "update";

	for (const rule of PROTECT_RULES) {
		const matchesPath = rule.paths.some(
			(pattern) =>
				minimatch(relativePath, pattern) || minimatch(filePath, pattern)
		);
		if (!matchesPath) {
			continue;
		}

		const isExcluded = rule.exclude.some(
			(pattern) =>
				minimatch(relativePath, pattern) || minimatch(filePath, pattern)
		);
		if (isExcluded) {
			continue;
		}

		const permission = rule.permissions[operation];
		if (permission === "deny") {
			const message =
				rule.message ||
				`[FDD] File "${relativePath}" is protected by ${rule.pitfallId}`;
			outputDeny(
				`🚫 ${message}\n\nOperation: ${operation}\nPitfall: ${rule.pitfallId} - ${rule.pitfallTitle}`
			);
			return;
		}
	}

	outputAllow();
}

function outputAllow() {
	const output = {
		hookSpecificOutput: {
			hookEventName: "PreToolUse",
			permissionDecision: "allow",
		},
	};
	console.log(JSON.stringify(output));
	process.exit(0);
}

function outputDeny(reason) {
	const output = {
		hookSpecificOutput: {
			hookEventName: "PreToolUse",
			permissionDecision: "deny",
			permissionDecisionReason: reason,
		},
	};
	console.log(JSON.stringify(output));
	process.exit(0);
}
